UNWANTED_ITEM_NAMES = {
    "YEKUN MEBLG",
    "YEKUN MƏBƏG",
    "EDV",
    "YAKUN MEBLEG",
    "YEKUN MEBLEG",
    "YEKUN MƏBLƏĞ",
    "YEKUN MƏBLƏG",
    "YAKUN MƏBƏG",
    "YƏKUN MƏBLƏĞ",
    "YEKUN MEBLOĞ",
    "ODENIUS USULU",
    "YEKUN MEBLOG",
    "YEKUN",
    "EDV CƏMİ",
    "NAGDSIZ",
    "KARTLA ÖDANILIB",
    "KARTLA ODENILIB",
    "KARTLA ÖDƏNİLİB",
    "OGENIS USULU",
    "TİCARƏT ƏLAVƏSİ",
    "TICARET ELAVE",
    "TICARET ELAVE",
    "TICARET ƏLAVƏSİ",
    "ODENIS USULU",
    "EDV CEMI",
    "CƏMİ",
    "CEMI",
    "TOTAL",
    "SUM",
    "İCMAL",
    "ICMAL",
}